export { getPersonsMapGames } from './getPersonsMapGames'
export { getPersonsMap } from './getPersonsMap'
export { transformGamesForChart } from './transformGamesForChart'
export { transformDataForTable } from './transformDataForTable'
export { getTransformedDataFromNumGames } from './getTransformedDataFromNumGames'
export { getTransformedDataFromBoolGames } from './getTransformedDataFromBoolGames'
