export { filterGamesByItsCount } from './filterGamesByItsCount'
export { filterGamesByRegExp } from './filterGamesByRegExp'
export { getGameByPath } from './getGameByPath'
export { getImgPathWithoutExt } from './getImgPathWithoutExt'
export { transformGamesForChart } from './transformGamesForChart'
